<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAL_SOF205\DAL_SOF205.csproj" />
    <ProjectReference Include="..\DTO_SOF205\DTO_SOF205.csproj" />
  </ItemGroup>

</Project>
